### ISSUE TITLE
BOJ 2504 괄호의 값(공통)

### ISSUE THREAD

**Issue by Sohyun043011** [SSAFY-09-D7/term1-group3#187]

**Comment by Sohyun043011** [comment]
진짜 모르겠습니다...

**Comment by 210-reverof** [comment]
스택을 이용한 후위연산 검색하셔서 나오는 자료들을 완전히 이해하면 그것을 응용해서 해결할 수 있을 것 같아요 !!

**Comment by SeungJong-Lee** [comment]
오늘 한 계산기 처럼 각 괄호가 나올때 어떤 동작을 수행해야하는지를 잘 고려하면 될거같아용~
