### ISSUE TITLE
BOJ 1303 전투

### ISSUE THREAD

**Issue by Sohyun043011** [SSAFY-09-D7/term1-group3#260]

**Comment by 210-reverof** [comment]
https://github.com/SSAFY-09-D7/term1-group3/issues/235

**Comment by Sohyun043011** [comment]
static 변수를 메인에서 선언하고 있어서 계속 안풀렸음 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
바보^^....
