### ISSUE TITLE
CODETREE 2개의 사탕

### ISSUE THREAD

**Issue by 210-reverof** [SSAFY-09-D7/term1-group3#410]
https://www.codetree.ai/training-field/frequent-problems/two-candies/description?page=1&pageSize=20&username=sheltonwon

**Comment by 210-reverof** [comment]
와 코드트리가 미래다

**Comment by SeungJong-Lee** [comment]
갈아탄거야?

**Comment by 210-reverof** [comment]
당분간 힐링 좀 하고 감
