### ISSUE TITLE
SWEA 2112 보호필름

### ISSUE THREAD

**Issue by SeungJong-Lee** [SSAFY-09-D7/term1-group3#412]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5V1SYKAaUDFAWu&

**Comment by 210-reverof** [comment]
닫은 시간을 보니 오빠 풀었던 거 호다닥 이슈여닫한 게 보이네효

**Comment by SeungJong-Lee** [comment]
ㅎㅎ.. 열고 풀까?
