### ISSUE TITLE
SWEA 4014 활주로 건설

### ISSUE THREAD

**Issue by 210-reverof** [SSAFY-09-D7/term1-group3#423]
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWIeW7FakkUDFAVH

**Comment by 210-reverof** [comment]
아 1

**Comment by SeungJong-Lee** [comment]
https://www.acmicpc.net/problem/14890
이거랑 같은문제 날먹하세요

**Comment by Holdm2t1ght** [comment]
@ssh5212
