### ISSUE TITLE
LG전자 코딩테스트 샘플문제

### ISSUE THREAD

**Issue by SeungJong-Lee** [SSAFY-09-D7/term1-group3#456]

**Comment by 210-reverof** [comment]
화이이이이ㅣ이이티이이ㅣ이잉!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 이승종 뿌실 수 있다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 비스포크 사주세요 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SeungJong-Lee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 비스포크는 삼성이라고오오오오오오
